### ISSUE TITLE
refresh-dashboard.rb exits if rate-limiting is not enabled

### ISSUE THREAD

**Issue by jason-riddle** [amznlabs/oss-dashboard#69]
This line assumes you have rate limiting enabled.

https://github.com/amznlabs/oss-dashboard/blob/b4fb17bbf08d1fdb89dc76522103f69807ca2866/refresh-dashboard.rb#L129

```ruby
context[:START_RATE_LIMIT]=client.rate_limit.remaining
```

If rate limiting is not enabled, a 404 along with the following message is returned

```json
{
  "message": "Rate limiting is not enabled.",
  "documentation_url": "https://developer.github.com/enterprise/2.4/v3"
}
```

and refresh-dashboard.rb exits.

**Comment by hyandell** [comment]
Thanks Jason :)

Is this when running on a private instance of GitHub Enterprise? If so - did you have to change other things to make the code point to the instance?

I don't see an obvious way in the API to tell if the code is looking at an enterprise instance, so I'm wondering if a solution would be to support the other changes you needed to make, and then I can use the existence of that configuration option or options as the condition for the rate limit call?

**Comment by jason-riddle** [comment]
Sorry, yes this is a Github Enterprise instance.

**Comment by jason-riddle** [comment]
In order to point to our github enterprise instance, I exported the following variable.

```bash
export OCTOKIT_API_ENDPOINT='https://github.super.secret.com/api/v3/'
```

**Comment by hyandell** [comment]
Thanks :)

So I'm thinking I'll check to see if that's set, and if it is then I'll turn off rate limiting.

Note though that I hard code urls to github.com in the dashboard; so that's going to be a big bug for you. Taking a quick look at the assumptions I've made:

* The XSLT that generates the dashboard has a lot.
* The pull source code assumes the source comes from github.com.
* Some of the database reports are putting in urls that point to github.com.

Given an API endpoint of https://github.super.secret.com/api/v3/; is it fair to convert that to a website of https://github.super.secret.com/ ?

**Comment by jason-riddle** [comment]
Yep, that's fair.

**Comment by hyandell** [comment]
Thanks. I'll make the rate limit change first, and spin up a separate issue for the hard coding of github.com.

On your side, you would be able to run a search and replace on the generated html files to fix as a hack.

**Comment by hyandell** [comment]
Check out the latest code and let me know if that resolves the initial issue here of rate_limiting. Would love to know if any other issues pop up for you; I don't have an enterprise instance to test against.

**Comment by hyandell** [comment]
Relates to #71.

**Comment by jason-riddle** [comment]
Very cool! Looks good. The only other small issue I can think of at the moment is running the following will still give an error.

```bash
ruby github-sync/util/get_rate_limit.rb
```

**Comment by hyandell** [comment]
Yeah, I figured the answer there was "don't run it" :)  I could add something to say that more politely :)

**Comment by hyandell** [comment]
I've applied the code (#71) to remove the github.com hardcoding, so it hopefully will work for you on your private instance without needing to edit the generated html.
